# DropsOverhaul Configuration #
Settings:
  # Handle old configs, do not touch
  Config-Version: 1
  # When /killdrops is used, what radius should the player be allowed to kill drops around them?
  Kill-Drops-Radius: 20
  # If the player's inventory is full, should the plugin delete junk blocks altogether, or should it drop the junk blocks and do the normal behavior
  Full-Inventory-Delete: true
  # List of materials to remove when mined
  Drops-To-Remove:
    - "DIRT"
    - "STONE"
    - "SAND"
    - "SANDSTONE"
    - "DIORITE"
    - "GRANITE"
    - "ANDESITE"
    - "GRAVEL"
    - "NETHERRACK"
    - "BLACKSTONE"
    - "BASALT"
    - "GRASS_BLOCK"
    - "TUFF"
    - "CALCITE"
    - "COBBLED_DEEPSLATE"
    - "DEEPSLATE"
    - "SMOOTH_BASALT"

Messages:
  Player-Only: "&cOnly players can use this command."
  No-Permission: "&cAccess denied."
  No-Permission-Killdrops-Radius: "&cYou don't have permission to specify a radius."
  Item-Delete: "&aSuccessfully removed %amount% items."
  Command:
    Help-Header: "&aDrops Overhaul Commands"
    Reload-Command: "&7/do reload &8- &eReloads the configuration."
    Kill-Drops-Command: "&7/do killdrops &8- &eKills nearby items."
    Reloaded: "&aSuccessfully reloaded configuration."
